services:
  api:
    build:
      context: .
      # Explicitly targeting your Mac's architecture
      platforms:
        - "linux/arm64"
    container_name: permit-api
    ports:
      - "3000:3000"
    volumes:
      - ./storage/packets:/usr/src/app/storage/packets
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - jaeger

  worker:
    build:
      context: .
      platforms:
        - "linux/arm64"
    container_name: permit-worker
    ports:
      - "3002:3001"
    # We run the build again here just in case, then start the worker
    command: sh -c "npm run build && node dist/workers/packetWorker.js"
    volumes:
      - ./storage/packets:/usr/src/app/storage/packets
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
      - jaeger

  # --- INFRASTRUCTURE ---
  postgres:
    image: postgres:15-alpine
    container_name: permit-postgres
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: permit-redis
    ports:
      - "6379:6379"

  # --- OBSERVABILITY STACK ---

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: permit-jaeger
    ports:
      - "16686:16686"
      - "4318:4318"
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  prometheus:
    image: prom/prometheus:latest
    container_name: permit-prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: permit-grafana
    ports:
      - "3001:3000"
    env_file:
      - .env
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
    depends_on:
      - prometheus
      - jaeger

volumes:
  pg_data:
